[build-system]
requires = [
  "setuptools>=48",
]
build-backend = "setuptools.build_meta"

[project]
name = "vllm-openvino"
description = "OpenVINO plugin for vLLM"
readme = "README.md"
license = {text = "Apache 2"}
# version to track the vLLM version support
version = "0.16.0"
dependencies = [
    "openvino >= 2026.1.0",
    #optimum is in dependency list of optimum-intel
    "optimum-intel[nncf] == 1.27.0",
    "vllm == 0.16.0",
]
requires-python = ">=3.9"

[project.entry-points."vllm.platform_plugins"]
openvino = "vllm_openvino:register"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["vllm_openvino*"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)


[tool.setuptools_scm]
# version_file = "vllm_openvino/_version.py" # currently handled by `setup.py:get_version()`

#[tool.uv]
## Never install torch, so that no dependencies can override it.
## This requires that torch is installed separately in the target environment.
#override-dependencies = [
#    "torch; sys_platform == 'never'",
#    "torchaudio; sys_platform == 'never'",
#    "torchvision; sys_platform == 'never'",
#]

[tool.uv.sources]
vllm = { git = "https://github.com/vllm-project/vllm", rev = "v0.16.0" }
