openvino:
  VLLM_OPENVINO_DEVICE: "CPU"
  VLLM_OPENVINO_KVCACHE_SPACE: 10
  VLLM_OPENVINO_ENABLE_QUANTIZED_WEIGHTS: true
  OPENVINO_RUNTIME_CONFIG:
    KV_CACHE_PRECISION: "u8"
    DYNAMIC_QUANTIZATION_GROUP_SIZE: "18446744073709551615"